[project]
name = "tamil-semantic-analyzer"
version = "1.0.0"
description = "Tamil Semantic Sentiment Analyzer with Gemini AI"
requires-python = ">=3.11,<3.12"

[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"
