# Railway deployment configuration
[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"

[env]
PORT = "5000"
FLASK_ENV = "production"